name: Notify Discord on Push

on:
  push:
    branches:
      - main

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: https://discord.com/api/webhooks/1392378414526103593/0cCpbWiPo62o26qLAHZZGJsf0Sjlw0bJATqEJ55xurVcW5fDfS18QtKmU-GXIFkBPfCB
          title: "Repository Updated"
          description: "A push was made to the repository. Check the latest changes on GitHub."
          color: 0x7289da
          username: "Repo Notifier Bot"
          avatar_url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
