name: Daily Update Siblings Ages

on:
  schedule:
    # Runs every day at midnight (UTC)
    - cron: '0 0 * * *'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  update-ages:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # If you have any dependencies, install them here
          pip install zoneinfo || true
          # Use tzdata as a fallback for Python < 3.9 if needed
          pip install tzdata

      - name: Run update script
        run: python .github/scripts/update_ages.py

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push if changed
        id: commit_changes
        run: |
          git add ages.json README.md
          if git diff --staged --quiet; then
            echo "No changes to commit"
            echo "CHANGES_MADE=false" >> $GITHUB_ENV
          else
            git commit -m "Auto-update siblings ages [skip ci]"
            git push
            echo "CHANGES_MADE=true" >> $GITHUB_ENV
          fi

      - name: Send Discord notification
        if: ${{ env.CHANGES_MADE == 'true' }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: https://discord.com/api/webhooks/1392378414526103593/0cCpbWiPo62o26qLAHZZGJsf0Sjlw0bJATqEJ55xurVcW5fDfS18QtKmU-GXIFkBPfCB
          title: "Siblings Ages Updated"
          description: "The ages.json and README.md files have been updated with the latest age information."
          color: 0x00ff00
          username: "Age Update Bot"
          avatar_url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
